---
title: "Song_NewData_Code"
author: "Team IG"
date: "12/03/2019"
output: html_document
---
  
```{r setup, include=FALSE}
pacman::p_load(readxl,dplyr,tidyverse,ggplot2,plotly,ggpubr,MASS,fitdistrplus,mediation,geepack,conf,car,knitr,gclus,scatterplot3d, ppcor,lme4,mediation,quantreg)
```


```{r}
newdata <- read.csv("/Applications/BU/BU/675 Statistical Practice  I/team-IG/paper/team-IG-master/new data.csv")
#data transformation: generate a new variable to measure the level of racial diversity
#Create a new dataset(data1) that includes generalized variety
#Have to change the raw number of White, Black, Hispanic to proportion of the whole population.
data1 <- newdata %>% 
  mutate(Black = BlackE/Totalpop) %>% 
  mutate(White = WhiteE/Totalpop) %>% 
  mutate(Hispanic = HispanicE/Totalpop) %>% 
  mutate(Racial_diversity=1-White^2-Black^2-Hispanic^2) %>%
  mutate(norm_Racial_diversity = Racial_diversity*(3/2))
```


```{r}
#Try to analysis the data in the single year (2010), which is the same year as the old dateset.
#Create a new dataset that contains only the data in the year of 2010 (data2)
data2 <- filter(data1,Year=="2010")

#Check the Cr plots for test model
fittest <- lm(Voe~Union+Urbanity+Unemployment+GDP_Per_Capita+Totalpop,data = data2)
summary(fittest)
par(mfrow=c(2,2))
plot(fittest)
crPlots(fittest)

#transformation
#fit1 seems to be the best with the least outliners and more valid assumptions
fit1 <- lm(log(Voe)~Union+Urbanity+Unemployment+GDP_Per_Capita+Totalpop,data = data2)
summary(fit1)
par(mfrow=c(2,2))
plot(fit1)
crPlots(fit1)

fit2 <- lm(log(Voe)~Union+Urbanity+Unemployment+log(GDP_Per_Capita)+log(Totalpop),data=data2)
summary(fit2)
par(mfrow=c(2,2))
plot(fit2)
crPlots(fit2)

#add racial diveristy
fit3 <- lm(log(Voe)~Union+Urbanity+Unemployment+log(GDP_Per_Capita)+log(Totalpop)+norm_Racial_diversity,data=data2)
summary(fit3)
par(mfrow=c(2,2))
plot(fit3)
crPlots(fit3)

#Mediation Analysis
model.tm1 <- lm(norm_Racial_diversity~Union+Urbanity+Unemployment+log(GDP_Per_Capita)+log(Totalpop),data=data2)
model.ty1 <- lm(log(Voe)~Union+norm_Racial_diversity+Urbanity+Unemployment+log(GDP_Per_Capita)+log(Totalpop),data=data2)
out.1 <- mediate(model.tm1,model.ty1,sims=1000,treat = "Union",mediator = "norm_Racial_diversity")
summary(out.1)
plot(out.1)
#In this case, we find the racial diversity does not have a mediation effect.
```



```{r}
#Analyze the data between the year of 2009 to the year of 2017
#Create a new dataset(data3) that excludes year between 2005 and 2008
#fit a linear regression without transformation
data3 <- filter(data1,Year>2008)
fit4 = lm(Voe ~ factor(Year)+Union+Urbanity+Unemployment+GDP_Per_Capita+Totalpop,data = data3)
summary(fit4)
par(mfrow=c(2,2))
plot(fit4)
crPlots(fit4)
```


```{r}
#Data transformation
fit5 = lm(log(Voe) ~ factor(Year)+Union+Urbanity+Unemployment+log(GDP_Per_Capita)+log(Totalpop),data = data3)
fittest1 = lm(log(Voe) ~ factor(Year)+Union+Unemployment+log(GDP_Per_Capita)+log(Totalpop),data = data3)
summary(fittest1)
summary(fit5)
par(mfrow=c(2,2))
plot(fit5)
crPlots(fit5)
#For each 1 percentage point increase in union density, there might be 3% decrease in Votional Training. exp(-0.020877) = 0.9793394.
```


```{r}
#Exclude DC (leverage points)
data4 <- filter(data3, State!="District of Columbia")
fit6 = lm(log(Voe) ~ factor(Year)+Union+Urbanity+Unemployment+log(GDP_Per_Capita)+log(Totalpop),data = data4)
summary(fit6)
par(mfrow=c(2,2))
plot(fit6)
crPlots(fit6)
```


```{r}
#Add racial diversity
fit7 = lm(log(Voe) ~ factor(Year)+Union+Urbanity+Unemployment+log(GDP_Per_Capita)+log(Totalpop)+norm_Racial_diversity,data = data3)
summary(fit7)
par(mfrow=c(2,2))
plot(fit7)
crPlots(fit7)
#1 percentage point increase in unionization would increase the vocational training amount to exp(0.16635) -> 1.16635 -> 17% larger?
```


```{r}
#Mediation Analysis
model.tm <- lm(norm_Racial_diversity~Union+Urbanity+Unemployment+log(GDP_Per_Capita)+log(Totalpop)+factor(Year),data=data3)
model.ty <- lm(log(Voe)~Union+norm_Racial_diversity+Urbanity+Unemployment+log(GDP_Per_Capita)+log(Totalpop)+factor(Year),data=data3)
out.2 <- mediate(model.tm,model.ty,sims=1000,treat = "Union",mediator = "norm_Racial_diversity")
summary(out.2)
plot(out.2)
#In this case, we find the racial diversity does not have a mediation effect.
```


```{r}
fit8 = lm(log(Voe) ~ factor(Year)+Union+Urbanity+Unemployment+log(GDP_Per_Capita)+log(StudentpopE),data = data3)
summary(fit8)
par(mfrow=c(2,2))
plot(fit8)
crPlots(fit8)

fit9 = lm(log(Voe) ~ factor(Year)+Union+Urbanity+Unemployment+log(GDP_Per_Capita)+log(StudentpopE)+ norm_Racial_diversity,data = data3)
summary(fit9)
par(mfrow=c(2,2))
plot(fit9)
crPlots(fit9)

#VOE concentrators, with studentpop
#interpret the model
#propotion of student 
#confounding variables (different variables)
```


```{r}
#Mediation Analysis
model.sm <- lm(norm_Racial_diversity~Union+Urbanity+Unemployment+log(GDP_Per_Capita)+log(StudentpopE)+factor(Year),data=data3)
model.sy <- lm(log(Voe)~Union+norm_Racial_diversity+Urbanity+Unemployment+log(GDP_Per_Capita)+log(StudentpopE)+factor(Year),data=data3)
out.3 <- mediate(model.sm,model.sy,sims=1000,treat = "Union",mediator = "norm_Racial_diversity")
summary(out.3)
plot(out.3)
#In this case, we find the racial diversity does not have a mediation effect.
```



